version: 0.1.{build}

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - git reset --hard HEAD
  - npm install -g @vue/cli
  - npm install

build_script:
  - npm run release

test: off
